### PR TITLE
chore(): Reformat lint to account for future subdirs

### PR DESCRIPTION
**Pull request by oliver-daniel**
Just doing everything as a PR to avoid accidents.

### CODE REVIEW

**Comment by bluestreak01** [comment]
does not work on windows due to single quoting the pattern:

image

**Comment by argshook** [comment]
@oliver-daniel is this PR still relevant?

**Comment by oliver-daniel** [comment]
Probably not. Vlad and I were pair-programming on getting a minor fix pushed through, and we ended up with divergent behaviour with my being on *nix and him on Windows.

**Comment by argshook** [comment]
okay, thanks for updating!

I'll close the PR then. Feel free to reopen if anything will change. Thanks!

**Pull request closed without merging**
